language: rust

env:
  global:
    - RUST_BACKTRACE=1
    - CRATE_NAME=urdf-viz
rust:
  - stable

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=x86_64-apple-darwin
      os: osx
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  # TODO update `api_key.secure`
  # - Create a `public_repo` GitHub token. Go to: https://github.com/settings/tokens/new
  # - Encrypt it: `travis encrypt 0123456789012345678901234567890123456789
  # - Paste the output down here
  api_key:
    secure: SzarbeIA/mYLRzVGntC+52C6qwCReC9//67+jcBNSR24/TsjXsultqLBHehzcAVCChuRIfetAlo2JscB4oCsT3rSXV0zB5yKlMDC0CDCG6r5dEPw6H6i79LBnetUAZUFh2qpC7s6yc33YxChE01mD5QgEpwjsycSr/5YsTAW45JYbiSe3dFeV/UChy2b2Ey3OK5ZqisdImvf8OnD0uaOyB0v0YunZj47uSDx4EmjD1UbaSPYE1nY7TcyYcf8O9yH5+4tZsrzSgNzhiQBswm9kJR6aKrJKj19V0+q81ppIAzoYXvjMmg3n+ngNM6Mh3OmSuSrpZmD8OHpWcKlnhFHKgMpmGO7yXliCcMO8FDdyiakQA0G4P+pqKonIP6n8+bnaglf/Y5CTvnS6Lkiuc94GHIw03t085x1Jy+GKdrklkUU+UK+Ygme97Tq7ESKbi369cax8GhtMkpLcXou94in1XyUVDZI3roj5QFUbvLrQL6IaASslBA6qP5BrXMJISInCFdrNOFbd5taUIwo79DkG+GKRghGNZgJXzxfhMQG/RHe2hMtfWDOtj6iAiCpXy4YOhfoNdb/vuP7kzkuGfzdgx8QRS8+2Tvq4Lji+/94/RyoSoUC1P/qauNym1j03M0O+6ZUehqXV9eodZjylGHD1Lk9rdpMzkRr82QsaUmPKZE=
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  on:
    # TODO Here you can pick which targets will generate binary releases
    # In this example, there are some targets that are tested using the stable
    # and nightly channels. This condition makes sure there is only one release
    # for such targets and that's generated using the stable channel
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
  provider: releases
  skip_cleanup: true

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never

addons:
  apt:
    packages:
      - xorg-dev
      - libglu1-mesa-dev