[package]
name = "urdf-viz"
version = "0.22.1"
authors = ["Takashi Ogura <t.ogura@gmail.com>"]
description = "URDF visualization"
license = "Apache-2.0"
keywords = ["robotics", "urdf", "visualization"]
categories = ["visualization"]
repository = "https://github.com/OTL/urdf-viz"
documentation = "http://docs.rs/urdf-viz"
readme = "README.md"
exclude = [".github/*", "img/*"]
edition = "2018"

[features]
default = ["use-assimp"]
use-assimp = ["assimp", "assimp-sys"]

[dependencies]
env_logger = "0.4.2"
thiserror = "1.0"
k = "0.21"
kiss3d = "0.28"
log = "0.4"
nalgebra = "0.23"
rand = "0.3.0"
serde = "1.0"
serde_derive = "1.0"
structopt = "0.3"
urdf-rs = "0.4.2"
rouille = "2.1.0"
assimp = { version = "0.3.1", optional = true }
assimp-sys = { version = "0.3.1", optional = true }

# for MacOS, waiting kiss3d 0.28.1?
[patch.crates-io]

kiss3d = { git = 'https://github.com/sebcrozet/kiss3d', rev='6274d50' }
