[package]
name = "urdf-viz"
version = "0.22.1"
authors = ["Takashi Ogura <t.ogura@gmail.com>"]
description = "URDF visualization"
license = "Apache-2.0"
keywords = ["robotics", "urdf", "visualization"]
categories = ["visualization"]
repository = "https://github.com/OTL/urdf-viz"
documentation = "http://docs.rs/urdf-viz"
readme = "README.md"
exclude = [".github/*", "img/*"]
edition = "2018"

[features]
default = ["use-assimp"]
use-assimp = ["assimp", "assimp-sys"]

# Note: k, kiss3d, nalgebra, serde, and urdf-rs are public dependencies.
[dependencies]
env_logger = "0.8"
k = "0.22"
kiss3d = "0.29"
log = "0.4"
nalgebra = "0.24"
rand = "0.8"
rouille = "3.0"
serde = { version = "1.0", features = ["derive"] }
structopt = "0.3"
thiserror = "1.0"
urdf-rs = "0.6"
assimp = { version = "0.3.1", optional = true }
assimp-sys = { version = "0.3.1", optional = true }
